### ISSUE TITLE
Implement Middleware Builder

### ISSUE THREAD

**Issue by 4lessandrodev** [4lessandrodev/ts-logs#11]
### Handler Builder

Implement a Handler builder to create a middleware and intercept the error and generate a log

```ts

app.use((err: Error, req: Request, res: Response, next: NextFunction) => {

    const origin = req.protocol + '://' + req.headers['host'] + req.originalUrl;
    const name = req.originalUrl?.replace(/\//, '');
    const uid = req.headers['uid'] as string ?? randomUUID();
    const ip = req.ip;

    const log = Log.init({ name, uid, origin, ip });

    const message = err.message;
    const stack = err.stack ?? '';
    const statusCode = 500;
    const data = JSON.stringify(req.body);
    const url = req.protocol + '://' + req.headers['host'] + req.originalUrl;

    const step = Step.stack({ message, name, stack, statusCode, url, data });

    const result = log.addStep(step);
    res.status(statusCode).json(result);
});



#### Example

```

- [x] Get uid from headers or generate a new one
- [x] Define a callback what to do after handler log. Default call response send log.
- [x] Ask for print
- [x] Ask for save local
- [x] Get keys from body as tags

```json

{
    "uid": "4f1c0880-5e93-4aa0-8e43-255a646457ac",
    "name": "route-03/error",
    "ip": "127.0.0.1",
    "origin": "http://localhost:3000/route-03/error",
    "createdAt": "2023-01-30T03:50:18.224Z",
    "steps": [
        {
            "uid": "f638da39-bc7e-40e8-a7ed-2dc29aafd381",
            "name": "route-03/error",
            "tags": ["attribute1", "notes", "hello"],
            "url": "http://localhost:3000/route-03/error",
            "stack": "Error: Internal Server Error\n    at /home/user/logs-app/dist/index.js:30:11\n    at Layer.handle [as handle_request] (/home/user/logs-app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/user/logs-app/node_modules/express/lib/router/route.js:144:13)\n    at Route.dispatch (/home/user/logs-app/node_modules/express/lib/router/route.js:114:3)",
            "data": "{\"attribute1\":\"data1\",\"hello\":{\"world\":\"42\"},\"notes\":[1,2,3]}",
            "statusCode": 500,
            "message": "Internal Server Error",
            "type": "stack",
            "createdAt": "2023-01-30T03:50:18.223Z"
        }
    ]
}

```

**Comment by 4lessandrodev** [comment]
#### Added initial express middleware option

```ts

import express from 'express';
import { LOGMiddleware } from 'ts-logs';

const app = express();
app.use(express.json());

// ...


// on last midleware on the place to handle errors use it

app.user(LOGMiddleware({ writeLocal: true });

app.liste(3000);

```
